name: Deploy React App
on: 
  push: 
    branches:
      - master
jobs: 
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test application
        run: npm run test
  my_lint:
    runs-on: ubuntu-latest
    needs: my_test
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint application
        run: npm run lint
  my_build: 
    runs-on: ubuntu-latest
    needs: my_lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...